apiVersion: v1
kind: ConfigMap
metadata:
  name: rhche
type: Opaque
data:
  infra-bootstrapper-binary-url: "http://rhche-rhche.192.168.64.9.nip.io/agent-binaries/linux_amd64/bootstrapper/bootstrapper"
  infra-machine-start-timeout: "5"
  infra-pvc-strategy: "common"
  infra-trust-certs: "true"
  multi-user: "true"
  che-host: "rhche-rhche.192.168.64.9.nip.io"
  workspace-storage: "/home/user/che/workspaces"
  local-conf-dir: "/etc/conf"
  che.logs.dir: "/data/logs"
  che.predefined.stacks.reload_on_start: "true"
  log-level: "INFO"
  port: "8080"
  remote-debugging-enabled: "false"
  workspaces-memory-limit: "2400"
  workspaces-memory-limit-max: "2400mb"
  enable-workspaces-autostart: "false"
  keycloak-github-endpoint: "NULL"
  che-server-java-opts: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=25 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms50m -Xmx180m -Dfile.encoding=UTF8"
  che-workspaces-java-opts: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m"
  che-openshift-secure-routes: "false"
  che-secure-external-urls: "false"
  che-openshift-precreate-subpaths: "false"
  che-fabric8-multitenant: "true"
  che-fabric8-user-service-endpoint: "http://fakeuserapi/api/user/services"
  che-fabric8-auth-endpoint: "http://fakeauth"
  che-fabric8-multicluster-oso-proxy-url: "http://fakeosoproxy"
  che-docker-enable-container-stop-detector: "false"
  che-api: "http://rhche-rhche.192.168.64.9.nip.io/api"
  che-websocket-endpoint: "ws://rhche-rhche.192.168.64.9.nip.io/api/websocket"
  che-workspace-logs: "/workspace_logs"
  che-keycloak-auth-server-url: "http://keycloak-rhche.192.168.64.9.nip.io/auth"
  che-keycloak-realm: "che"
  che-keycloak-client-id: "che-public"
  che-workspace-server-ping-success-threshold: "2"
  che-limits-user-workspaces-run-count: "1"
  che.workspace.agent.dev.inactive_stop_timeout_ms: "1800000"
